###
GET http://localhost:3000/movies

###
GET http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0

###
GET http://localhost:3000/movies?genre=Crime

###
//añadir una pelicula
POST  http://localhost:3000/movies
Content-Type: application/json

{
    "title":"el buen padre",
    "year": 1975,
    "director": "Francia Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre":[
        "Drama",
        "Crime"
    ],
     "rate": 9.0
}

###
PATCH  http://localhost:3000/movies/6a360a18-c645-4b47-9a7b-2a71babbf3e0
Content-Type: application/json

{
    "year": "2021"
}